"use client"
import { useMemo, useState } from "react"
import Link from "next/link"
import Image from "next/image"
import { ArrowUpRight, Search } from "lucide-react"
import type { BlogPost } from "@/lib/blog"
import styles from "./blog-posts-grid.module.css"
export function BlogPostsGrid({ posts }: { posts: BlogPost[] }) { const categories=["ทั้งหมด",...Array.from(new Set(posts.map(p=>p.category)))];const [active,setActive]=useState("ทั้งหมด");const [query,setQuery]=useState("");const filtered=useMemo(()=>posts.filter(p=>(active==="ทั้งหมด"||p.category===active)&&(!query.trim()||`${p.title} ${p.description}`.toLowerCase().includes(query.trim().toLowerCase()))),[active,posts,query]);const [featured,...rest]=filtered;return <div><div className={styles.controls}><label className={styles.search}><Search size={16} aria-hidden="true"/><span className="sr-only">ค้นหาบทความ</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาบทความ..."/></label><div className={styles.filters} role="group" aria-label="กรองหมวดหมู่">{categories.map(c=><button key={c} type="button" aria-pressed={active===c} onClick={()=>setActive(c)}>{c}</button>)}</div></div><p className={styles.result} aria-live="polite">พบ {filtered.length} บทความ</p>{featured?<div className={styles.grid}><Post post={featured} lead/><div className={styles.rest}>{rest.map(post=><Post key={post.slug} post={post}/>)}</div></div>:<div className={styles.empty} role="status"><p>ไม่พบบทความที่ตรงกับการค้นหา</p><button type="button" onClick={()=>{setQuery("");setActive("ทั้งหมด")}}>ล้างตัวกรอง</button></div>}</div> }
function Post({post,lead=false}:{post:BlogPost;lead?:boolean}){return <Link href={`/blog/${post.slug}`} className={`${styles.card} ${lead?styles.lead:""}`}><Image src={articleCover(post)} alt="" fill sizes={lead?"(max-width:700px) 100vw,60vw":"(max-width:700px) 100vw,40vw"} className={styles.image}/><div className={styles.overlay}/><div className={styles.copy}><span>{post.category} · {post.readTime}</span><h3>{post.title}</h3><p>{post.description}</p><b>อ่านต่อ <ArrowUpRight size={15} aria-hidden="true"/></b></div></Link>}

function articleCover(post: BlogPost) { const names: Record<string,string> = {"website-2026-trend-thurai-thai-tong-ru":"trends","content-marketing-samnab-website-thurakit-thai":"content","an-analytics-website-yang-rai-hai-pen-prayot-tor-thurakit":"analytics"}; return names[post.slug] ? `/creative-home/images/articles/editorial-${names[post.slug]}.webp` : post.image }
